### ISSUE TITLE
Confirm names

### ISSUE THREAD

**Issue by lowell80** [Kintyre/shinnecock-agent#2]
Confirm the following names:

- [x] Repo name
- [x] Executable script is called `kinytre_speedtest` (defined in setup.py)
- [x] Name of python package `KintyreSpeedTestStandalone`.  (We don't want to change this after publishing it to pypi; also defined in setup.py)

Lowell's thoughts:

 * I think repo name is probably good enough.  GitHub handles redirect nicely.
 * I think the python package name should change.  I'm thinking something like `kintyre-speedtest-agent` would be better.  (Our other package is named `kintyre-splunk-conf`, just for comparison purposes)

**Comment by brian-kennedy** [comment]
Repo:  shinnecock-agent
Script:  kintyre-speedtest.py
Package:  kintyre-speedtest-agent

**Comment by lowell80** [comment]
Brian,

Minor changes required upon further investigation.  Unless I hear otherwise I'll assume you're fine with this.

I oversimplified this in the original ticket.  Here's the python naming:

 * Python module file:   `kintyre_speedtest.py`  (Visible in the repo)
 * Executable name:   `kintyre-speedtest`  (The name of the CLI interface; added to the user's PATH)

Reasons:

 1. The installed "executable script" can't end with `.py`  (it will have no extension on Linux/Mac, and `.exe` on Windows);  This isn't visible until after the package is installed.
 2. The internal module can be called `kintyre_speedtest.py`  (Dashes aren't allowed in the name of Python modules.)  This name will appear in the repo, and can be executed directly for testing.
